source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target "ProvaConcrete.xcodeproj" do
  pod 'AlamofireSwiftyJSON'
  pod 'AlamofireImage'
  pod 'Mantle', '~> 2.0'
  pod 'MTLManagedObjectAdapter', '~> 1.0'
end
