source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def shared_pods
	pod 'SDWebImage', '~> 3.7.3'
	pod 'SVProgressHUD'
	pod 'Alamofire'
	pod 'ReachabilitySwift', '~> 3'
	pod 'CoolDesignables'
end

target "DesafioIOS" do
    shared_pods
end

target "DesafioIOSTests" do
    shared_pods
end
