# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Git Java' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Git Java
    pod 'Alamofire', '~> 4.0'
    pod 'Kingfisher', '~> 4.0'
    #pod 'SwiftLint'


  target 'Git JavaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
