# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JavaPop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Font-Awesome-Swift', '~> 1.7'
pod 'Alamofire'
pod 'AlamofireObjectMapper', '~> 5.0'

  # Pods for JavaPop

  target 'JavaPopTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
