# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'GitHubAllStars' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafio-ios
  pod 'Alamofire'
  pod 'ObjectMapper', '~>3.0.0'
  pod 'AlamofireObjectMapper', '~> 5.0.0'
  pod 'SDWebImage', '~> 4.1.2'
end
